services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=1q2w3e$R
      - MYSQL_DATABASE=usermessages
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=1q2w3e$R
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql

  rest-service:
    build: .
    restart: on-failure
    ports:
      - 8100:8100
    depends_on:
      - mysqldb
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url":"jdbc:mysql://spring-boot-jwt-demo-mysqldb-1:3306/usermessages",
            "spring.datasource.username":"mysql",
            "spring.datasource.password":"1q2w3e$R",
            "spring.user.datasource.driver-class-name":"com.mysql.jdbc.Driver",
            "server.port":"8100",
            "spring.flyway.baselineOnMigrate":"true"
         }'
    volumes:
      - .m2:/root/.m2

volumes:
  db: